package ar.edu.um.entidad;

// Generated Feb 2, 2014 7:21:27 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Tema generated by hbm2java
 */
@Entity
@Table(name = "tema", catalog = "canario")
@XmlRootElement(name = "tema")
public class Tema implements java.io.Serializable {

	private int idTema;
	private String nombre;	

	public Tema() {
	}

	public Tema(int idTema, String nombre) {
		this.idTema = idTema;
		this.nombre = nombre;
	}

	@Id
	@Column(name = "idTema", unique = true, nullable = false)
	@XmlElement
	public int getIdTema() {
		return this.idTema;
	}

	public void setIdTema(int idTema) {
		this.idTema = idTema;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	@XmlElement
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}
