package ar.edu.um.entidad;

// Generated Feb 2, 2014 7:21:27 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * TipoUsuario generated by hbm2java
 */
@Entity
@Table(name = "tipoUsuario", catalog = "canario")
@XmlRootElement(name = "tipoUsuario")
public class TipoUsuario implements java.io.Serializable {

	private int idtipoUsuario;
	private String nombre;

	public TipoUsuario() {
	}

	public TipoUsuario(int idtipoUsuario, String nombre) {
		this.idtipoUsuario = idtipoUsuario;
		this.nombre = nombre;
	}

	@Id
	@Column(name = "idtipoUsuario", unique = true, nullable = false)
	@XmlElement
	public int getIdtipoUsuario() {
		return this.idtipoUsuario;
	}

	public void setIdtipoUsuario(int idtipoUsuario) {
		this.idtipoUsuario = idtipoUsuario;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	@XmlElement
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
